package maestro.cli.mixin

import picocli.CommandLine

class AppleTeamIdMixin {
    @CommandLine.Option(
        names = ["--apple-team-id"],
        description = ["The Team ID is a unique 10-character string generated by Apple that is assigned to your team's apple account."],
        hidden = true,
    )
    var appleTeamId: String? = null
}
