#!/bin/bash

REMOTE_PATH=/data/local/tmp/tmp.mp4

adb shell screenrecord --bit-rate '100000' $REMOTE_PATH &
SR_PID=$!

function stop() {
  kill $SR_PID || true
  wait $(jobs -p)
}

trap stop EXIT

maestro test "$@"

stop

sleep 1

adb pull $REMOTE_PATH /tmp/tmp.mp4

ID=$(uuidgen)

echo $ID

VIDEO_PATH=$(http -f POST https://maestro-record.ngrok.io/render screenRecording@/tmp/tmp.mp4 | jq -r .url)

http GET "https://maestro-record.ngrok.io$VIDEO_PATH" > /tmp/out.mp4
open /tmp/out.mp4
