rootProject.name = "maestro"

include("maestro-utils")
include("maestro-android")
include("maestro-cli")
include("maestro-client")
include("maestro-ios")
include("maestro-network-proxy")
include("maestro-network-proxy:android")
include("maestro-network-proxy:android-unsafe")
include("maestro-orchestra")
include("maestro-orchestra-models")
include("maestro-orchestra-proto")
include("maestro-proto")
include("maestro-studio:server")
include("maestro-studio:web")
include("maestro-test")
include("examples:apps:android-app")
//include("examples:samples")
//findProject(":examples:samples")?.name = "samples"
