name: Report a bug
description: You have a problem with Maestro.
body:
  - type: markdown
    attributes:
      value: >
        ### Thank you for using Maestro!


        Before creating a new issue, please first search the [existing issues]
        and make sure it hasn't been reported before.


        If you are sure that you have found a bug that hasn't been reported yet,
        or if our documentation doesn't have an answer to what you're looking
        for, then please fill out this template.


        ---


        [existing issues]: https://github.com/mobile-dev-inc/maestro
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues and didn't find mine.
        required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: >
        Create a [minimal, reproducible example] that:

        1. Demonstrates the problem

        2. Explains how to reproduce the problem with detailed step-by-step
        instructions


        **In addition to the detailed step-by-step instructions**, you must include
        information about the device you're encountering the issue on
        (e.g. physical Android or iOS simulator), and the OS version
        (e.g. Android 9, Android 14 with Play Services, or iOS 18).


        **It's critical that you include your test flow file**. In general, try
        to include as much additional details as possible to make it easier for
        us to understand and fix the problem. Screenshots and videos are
        welcome.

           > [!TIP]
          > If you're recording a video on Android, we recommend enabling these options to show taps and gestures:
          > ```
          > adb shell settings put system show_touches 1
          > adb shell settings put system pointer_location 1
          > ```


         > [!WARNING]
        > Issues that cannot be reproduced are much more likely to be closed.


        [minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
      placeholder: |
        Example good reproduction steps:
        1. Clone https://github.com/your_username/your_repo_with_bug and `cd` into it
        2. Start Android emulator (Pixel 7, API 34, with Google Play)
        3. Build app: `./gradlew :app:assembleDebug`
        4. Run the problematic flow and see it fail: `maestro test .maestro/flow.yaml`
  - type: textarea
    validations:
      required: true
    attributes:
      label: Actual results
      description: Please explain what is happening.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected results
      description: Please explain what you expect to happen.
  - type: textarea
    validations:
      required: true
    attributes:
      label: About app
      description: >
        Include information about the app you're testing:
      
        - Is this an open source or closed source project?
          - If open source, please share link to the repo
          - If closed source, please share app binary and/or an isolated, reproducible sample
        - Is this a native or cross-platform app?

        - Framework used to build the app
          - e.g. UIKit, SwiftUI, Android Views, Compose, React Native, or NativeScript
          - If applicable, version of the framework (e.g. Flutter 3.22.0, Compose 1.62.0)
          - If applicable, minimum and target Android SDK/iOS version (e.g. minSdk 21, targetSdk 34)
      placeholder: |
        The info you enter here will make it easier to resolve your issue. For example:
        - This is an open source app, available at https://github.com/wikimedia/wikipedia-ios
        - It's a native iOS app. There is also an Android version, but the issue is only on iOS.
        - It's built mainly with UIKit, minimum iOS deployment target is 13.0
      
  - type: textarea
    validations:
      required: true
    attributes:
      label: About environment
      description: |
        Include information about machine you're running Maestro on:
      
        - Java version (e.g. OpenJDK 17, Eclipse Temurin 8). To find it, run `java -version`
        - OS and its version (e.g. macOS 13.1 Ventura, Ubuntu 24.04, Arch (btw))
        - Processor architecture (x86_64, arm64)
      placeholder: |
        The info you enter here will make it easier to resolve your issue. For example:
        - I'm on M1 MacBook Air, with macOS 14.5 Sonoma and Xcode 15.4.
  - type: textarea
    attributes:
      label: Logs
      description: >
        Include the full logs of the command you're running. The zip files
        created with `maestro bugreport` can be uploaded here as well.


        Things to keep in mind:


        - If you're running more than single command, include its logs in a
          separate backticks block.


        - If the logs are too large to be uploaded to Github, you may upload
          them as a `txt` file or use online tools like https://pastebin.com and
          share the link. Just make sure the link won't break in the future.


        - **Do not upload screenshots of text**. Instead, use code blocks or the
          above mentioned ways to upload logs.


        - **Make sure the logs are well formatted**. If you post garbled logs, it
          will make it harder for us to help you.
      value: |
        <details>
        <summary>Logs</summary>

        ```
        <!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
        ```

        </details>
  - type: input
    validations:
      required: true
    attributes:
      label: Maestro version
      description: >
        Provide version of Maestro CLI where the problem occurs. Run
        `maestro --version` to find out.
      placeholder: 1.36.0
  - type: dropdown
    validations:
      required: true
    attributes:
      label: How did you install Maestro?
      options:
        - install script (https://get.maestro.mobile.dev)
        - Homebrew
        - built from source (please include commit hash in the text area below)
        - other (please specify in the text area below)
      default: 0
  - type: textarea
    validations:
      required: false
    attributes:
      label: Anything else?
      description: >
        Links? Other issues? StackOverflow threads? Anything that will give us
        more context about the issue you are encountering will be helpful.

         > [!TIP]
        > You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: markdown
    attributes:
      value: >
        Now that you've filled all the required information above, you're ready
        to submit the issue.


        **Please check what your issue looks like after creating it**. If it
        contains garbled code and logs, please take some time to adjust it so
        it's easier to parse.


        **Try reading your issue as if you were seeing it for the first time**.
        Does it read well? Is it easy to understand? Is the formatting correct?
        If not, please improve it.


        Thank you for helping us improve Maestro and keeping our issue tracker
        in a good shape!
