name: FoldableFixture
options:
  bundleIdPrefix: com.maestro.foldable
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

targets:
  FoldableFixture:
    type: application
    platform: iOS
    sources:
      - FoldableFixture
    info:
      path: FoldableFixture/Info.plist
      properties:
        CFBundleDisplayName: Foldable
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.maestro.foldable
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_ALLOWED: NO
