#!/usr/bin/env sh
set -eu

# Runs all tests in the workspaces directory.

command -v maestro >/dev/null 2>&1 || { echo "maestro is required" && exit 1; }

[ "$(basename "$PWD")" = "e2e" ] || { echo "must be run from e2e directory" && exit 1; }

FAILED=false

# Run passing tests
for workspace_dir in ./workspaces/*; do
	echo "run passing tests for app $workspace_dir"

	maestro test --include-tags passing --exclude-tags ios "$workspace_dir" || FAILED=true
done

# Run failing tests
for workspace_dir in ./workspaces/*; do
	echo "run failing tests for app $workspace_dir"

	maestro test --include-tags failing --exclude-tags ios "$workspace_dir" && FAILED=true
done

if [ "$FAILED" = true ]; then
  echo "Some tests failed"
  exit 1
fi
