#!/usr/bin/env sh
set -eu

# Runs all web tests in the workspaces directory.

command -v maestro >/dev/null 2>&1 || { echo "maestro is required" && exit 1; }

[ "$(basename "$PWD")" = "e2e" ] || { echo "must be run from e2e directory" && exit 1; }

ALL_PASS=true

_h1() { printf "=>\n=> %s\n=>\n" "$1"; }
_h2() { printf "==> [%s] %s\n" "$1" "$2"; }
_h3() { printf "==> [%s] [%s] => %s\n" "$1" "$2" "$3"; }

exclude_tags="android,ios,cloud"
platform="web"

mkfifo pipe
trap 'rm -f pipe' EXIT

export MAESTRO_EXAMPLE="test-value"  # Relied upon in a test

app_name="demo_app"
workspace_dir="./workspaces/$app_name/web_flows"

_h1 "run tests for app \"$app_name\" on platform \"$platform\""
_h2 "$app_name" "run web tests"

while IFS= read -r line; do
	_h3 "$app_name" "web" "$line"
done < pipe &

maestro --verbose --platform "$platform" test --headless --include-tags web --exclude-tags "$exclude_tags" "$workspace_dir" 1>pipe 2>&1 \
	|| { _h2 "$app_name" "FAIL! Expected all pass, but at least some failed instead"; ALL_PASS=false; }

if [ "$ALL_PASS" = "false" ]; then
	_h1 "FAILURE: some tests failed!"
	exit 1
else
	_h1 "SUCCESS: all tests passed!"
fi