#!/usr/bin/env sh
set -eu

# Updates the samples that are hosted in mobile.dev's GCS bucket ($SAMPLES_URL).
# The samples are for use with `maestro download-samples` command.

[ "$(basename "$PWD")" = "e2e" ] || { echo "must be run from e2e directory" && exit 1; }

command -v curl >/dev/null 2>&1 || { echo "curl is required" && exit 1; }

SAMPLES_URL="gs://mobile.dev/samples/samples.zip"

if [ ! -d apps/ ]; then
  ./download_apps
fi

rm -rf samples/ samples.zip
mkdir -p samples/
cp -r apps/wikipedia.apk apps/Wikipedia.zip samples/
cp -r workspaces/wikipedia/* samples/
cd samples/

zip -r -q ../samples.zip . -x "/**/.*" -x "__MACOSX"

cd ..

gsutil cp samples.zip "gs://mobile.dev/samples/samples.zip"
gsutil acl ch -r -u AllUsers:R "gs://mobile.dev/samples/samples.zip"
