package maestro.studio

import com.fasterxml.jackson.annotation.JsonProperty
import io.ktor.server.engine.embeddedServer
import io.ktor.server.http.content.singlePageApplication
import io.ktor.server.netty.Netty
import io.ktor.server.routing.routing
import maestro.Maestro
import java.util.UUID

data class DeviceScreen(
    val screenshot: String,
    val width: Int,
    val height: Int,
    val elements: List<UIElement>,
)

data class UIElementBounds(
    val x: Int,
    val y: Int,
    val width: Int,
    val height: Int,
)

data class UIElement(
    val id: UUID, // Autogenerated uuid to make this easier to work with on the frontend
    val bounds: UIElementBounds?,
    val resourceId: String?,
    val resourceIdIndex: Int?,
    val text: String?,
    val textIndex: Int?
)

enum class ReplCommandStatus {
    @JsonProperty("pending")
    PENDING,
    @JsonProperty("running")
    RUNNING,
    @JsonProperty("success")
    SUCCESS,
    @JsonProperty("error")
    ERROR,
    @JsonProperty("canceled")
    CANCELED,
}

data class ReplCommand(
    val id: String,
    val yaml: String,
    val status: ReplCommandStatus,
)

data class Repl(
    val commands: List<ReplCommand>
)

object MaestroStudio {

    fun start(port: Int, maestro: Maestro) {
        embeddedServer(Netty, port = port) {
            routing {
                DeviceScreenService.routes(this, maestro)
                singlePageApplication {
                    useResources = true
                    filesPath = "web"
                    defaultPage = "index.html"
                }
            }
        }.start()
    }
}
