/*
 *
 *  Copyright (c) 2022 mobile.dev inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *
 */

package maestro.cli.command

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import kotlinx.coroutines.runBlocking
import maestro.TreeNode
import maestro.cli.App
import maestro.cli.CliError
import maestro.cli.DisableAnsiMixin
import maestro.cli.ShowHelpMixin
import maestro.cli.analytics.Analytics
import maestro.cli.analytics.PrintHierarchyFinishedEvent
import maestro.cli.analytics.PrintHierarchyStartedEvent
import maestro.cli.report.TestDebugReporter
import maestro.cli.session.MaestroSessionManager
import maestro.cli.view.yellow
import maestro.device.DeviceService
import maestro.device.DeviceService.withPlatform
import maestro.device.Platform
import maestro.utils.CliInsights
import maestro.utils.Insight
import maestro.utils.chunkStringByWordCount
import picocli.CommandLine
import picocli.CommandLine.Option
import java.lang.StringBuilder

@CommandLine.Command(
    name = "hierarchy",
    description = [
        "Print out the view hierarchy of the connected device"
    ]
)
class PrintHierarchyCommand : Runnable {

    @CommandLine.Mixin
    var disableANSIMixin: DisableAnsiMixin? = null

    @CommandLine.Mixin
    var showHelpMixin: ShowHelpMixin? = null

    @CommandLine.ParentCommand
    private val parent: App? = null

    @CommandLine.Option(
        names = ["--android-webview-hierarchy"],
        description = ["Set to \"devtools\" to use Chrome dev tools for Android WebView hierarchy"],
        hidden = true,
    )
    private var androidWebViewHierarchy: String? = null

    @CommandLine.Option(
        names = ["--reinstall-driver"],
        description = ["Reinstalls driver before running the test. On iOS, reinstalls xctestrunner driver. On Android, reinstalls both driver and server apps. Set to false to skip reinstallation."],
        negatable = true,
        defaultValue = "true",
        fallbackValue = "true"
    )
    private var reinstallDriver: Boolean = true

    @Option(
        names = ["--apple-team-id"],
        description = ["The Team ID is a unique 10-character string generated by Apple that is assigned to your team's Apple account."],
        hidden = true
    )
    private var appleTeamId: String? = null

    @CommandLine.Option(
        names = ["--compact"],
        description = ["Output in CSV format with element_num,depth,attributes,parent_num columns"],
        hidden = false
    )
    private var compact: Boolean = false

    @CommandLine.Option(
        names = ["--device-index"],
        description = ["The index of the device to run the test on"],
        hidden = true
    )
    private var deviceIndex: Int? = null

    override fun run() {
        TestDebugReporter.install(
            debugOutputPathAsString = null,
            flattenDebugOutput = false,
            printToConsole = parent?.verbose == true,
        )

        val platform = parent?.platform ?: "unknown"
        val startTime = System.currentTimeMillis()
        Analytics.trackEvent(PrintHierarchyStartedEvent(platform = platform))

        val effectiveDeviceId: String? = when {
            parent?.deviceId != null -> parent.deviceId
            deviceIndex != null -> null
            else -> {
                val platformFilter = parent?.platform?.let { Platform.fromString(it) }
                val connectedDevices = DeviceService.listConnectedDevices().withPlatform(platformFilter)
                when (connectedDevices.size) {
                    0 -> null
                    1 -> connectedDevices[0].instanceId
                    else -> {
                        val hint = if (platformFilter == null) {
                            " You can also narrow by platform using --platform <android|ios>."
                        } else ""
                        throw CliError("Multiple devices connected. Please specify a device using --device <id>.$hint")
                    }
                }
            }
        }

        MaestroSessionManager.newSession(
            host = parent?.host,
            port = parent?.port,
            driverHostPort = parent?.driverHostPort,
            teamId = appleTeamId,
            deviceId = effectiveDeviceId,
            platform = parent?.platform,
            reinstallDriver = reinstallDriver,
            deviceIndex = deviceIndex
        ) { session ->
            runBlocking { session.maestro.setAndroidChromeDevToolsEnabled(androidWebViewHierarchy == "devtools") }
            val callback: (Insight) -> Unit = {
                if (it.level != Insight.Level.NONE) {
                    val message = StringBuilder()
                    val level = it.level.toString().lowercase().replaceFirstChar(Char::uppercase)
                    message.append(level.yellow() + ": ")
                    it.message.chunkStringByWordCount(12).forEach { chunkedMessage ->
                        message.append("$chunkedMessage ")
                    }
                    System.err.println(message.toString())
                }
            }
            val insights = CliInsights

            insights.onInsightsUpdated(callback)

            val tree = runBlocking { session.maestro.viewHierarchy() }.root

            insights.unregisterListener(callback)

            val outputContent = if (compact) {
                val nodeToId = mutableMapOf<TreeNode, Int>()
                val csv = StringBuilder()
                var counter = 0
                tree?.aggregate()?.forEach { node ->
                    nodeToId[node] = counter++
                }
                processTreeToCSV(tree, 0, null, nodeToId, csv)
                "element_num,depth,attributes,parent_num\n$csv"
            } else {
                jacksonObjectMapper()
                    .setSerializationInclusion(JsonInclude.Include.NON_NULL)
                    .writerWithDefaultPrettyPrinter()
                    .writeValueAsString(tree)
            }

            print(outputContent)
        }

        val duration = System.currentTimeMillis() - startTime
        Analytics.trackEvent(PrintHierarchyFinishedEvent(
            platform = platform,
            success = true,
            durationMs = duration
        ))
        Analytics.flush()
    }

    private fun processTreeToCSV(
        node: TreeNode?,
        depth: Int,
        parentId: Int?,
        nodeToId: Map<TreeNode, Int>,
        csv: StringBuilder
    ) {
        if (node == null) return

        val nodeId = nodeToId[node] ?: return

        val attributesList = mutableListOf<String>()

        node.attributes.forEach { (key, value) ->
            if (value.isNotEmpty() && value != "false") {
                attributesList.add("$key=$value")
            }
        }

        if (node.clickable == true) attributesList.add("clickable=true")
        if (node.enabled == true) attributesList.add("enabled=true")
        if (node.focused == true) attributesList.add("focused=true")
        if (node.checked == true) attributesList.add("checked=true")
        if (node.selected == true) attributesList.add("selected=true")

        val attributesString = attributesList.joinToString("; ")
        val escapedAttributes = attributesString.replace("\"", "\"\"")

        csv.append("$nodeId,$depth,\"$escapedAttributes\",${parentId ?: ""}\n")

        node.children.forEach { child ->
            processTreeToCSV(child, depth + 1, nodeId, nodeToId, csv)
        }
    }

    private fun removeEmptyValues(tree: TreeNode?): TreeNode? {
        if (tree == null) {
            return null
        }

        return TreeNode(
            attributes = tree.attributes.filter {
                it.value != "" && it.value.toString() != "false"
            }.toMutableMap(),
            children = tree.children.map { removeEmptyValues(it) }.filterNotNull(),
            checked = if(tree.checked == true) true else null,
            clickable = if(tree.clickable == true) true else null,
            enabled = if(tree.enabled == true) true else null,
            focused = if(tree.focused == true) true else null,
            selected = if(tree.selected == true) true else null,
        )
    }
}
