/*
 *
 *  Copyright (c) 2022 mobile.dev inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *
 */

package maestro.cli.command

import maestro.cli.App
import maestro.cli.CliError
import maestro.cli.DisableAnsiMixin
import maestro.cli.ShowHelpMixin
import maestro.cli.analytics.Analytics
import maestro.cli.analytics.PrintHierarchyFinishedEvent
import maestro.cli.analytics.PrintHierarchyStartedEvent
import maestro.cli.report.TestDebugReporter
import maestro.cli.session.MaestroSessionManager
import maestro.device.DeviceService
import maestro.device.DeviceService.withPlatform
import maestro.device.Platform
import picocli.CommandLine
import picocli.CommandLine.Option

@CommandLine.Command(
    name = "hierarchy",
    description = [
        "Print out the view hierarchy of the connected device"
    ]
)
class PrintHierarchyCommand : Runnable {

    @CommandLine.Mixin
    var disableANSIMixin: DisableAnsiMixin? = null

    @CommandLine.Mixin
    var showHelpMixin: ShowHelpMixin? = null

    @CommandLine.ParentCommand
    private val parent: App? = null

    @CommandLine.Option(
        names = ["--android-webview-hierarchy"],
        description = ["Set to \"devtools\" to use Chrome dev tools for Android WebView hierarchy"],
        hidden = true,
    )
    private var androidWebViewHierarchy: String? = null

    @CommandLine.Option(
        names = ["--reinstall-driver"],
        description = ["Reinstalls driver before running the test. On iOS, reinstalls xctestrunner driver. On Android, reinstalls both driver and server apps. Set to false to skip reinstallation."],
        negatable = true,
        defaultValue = "true",
        fallbackValue = "true"
    )
    private var reinstallDriver: Boolean = true

    @Option(
        names = ["--apple-team-id"],
        description = ["The Team ID is a unique 10-character string generated by Apple that is assigned to your team's apple account."],
        hidden = true
    )
    private var appleTeamId: String? = null

    @CommandLine.Option(
        names = ["--compact"],
        description = ["Output in CSV format with element_num,depth,attributes,parent_num columns"],
        hidden = false
    )
    private var compact: Boolean = false

    @CommandLine.Option(
        names = ["--device-index"],
        description = ["The index of the device to run the test on"],
        hidden = true
    )
    private var deviceIndex: Int? = null

    override fun run() {
        TestDebugReporter.install(
            debugOutputPathAsString = null,
            flattenDebugOutput = false,
            printToConsole = parent?.verbose == true,
        )

        val platform = parent?.platform ?: "unknown"
        val startTime = System.currentTimeMillis()
        Analytics.trackEvent(PrintHierarchyStartedEvent(platform = platform))

        val effectiveDeviceId: String? = when {
            parent?.deviceId != null -> parent.deviceId
            deviceIndex != null -> null
            else -> {
                val platformFilter = parent?.platform?.let { Platform.fromString(it) }
                val connectedDevices = DeviceService.listConnectedDevices().withPlatform(platformFilter)
                when (connectedDevices.size) {
                    0 -> null
                    1 -> connectedDevices[0].instanceId
                    else -> {
                        val hint = if (platformFilter == null) {
                            " You can also narrow by platform using --platform <android|ios>."
                        } else ""
                        throw CliError("Multiple devices connected. Please specify a device using --device <id>.$hint")
                    }
                }
            }
        }

        // W4: the device read routes to the device-core seam via `driver.hierarchy()`, a roadmap
        // verb that throws NotImplemented until device-core ships a hierarchy dump — the intended
        // coverage signal.
        // W2: `maestro.TreeNode` is deleted, and `DeviceCoreDriver.hierarchy()` returns `Nothing`
        // (device-core exposes no hierarchy dump type yet), so the call can only throw. The
        // host-side CSV/JSON formatting that consumed TreeNode is removed with the type; it returns
        // once device-core ships a real hierarchy read.
        MaestroSessionManager.newDeviceCoreSession(
            host = parent?.host,
            port = parent?.port,
            driverHostPort = parent?.driverHostPort,
            deviceId = effectiveDeviceId,
            platform = parent?.platform?.let { Platform.fromString(it) },
        ) { driver, _, _ ->
            driver.hierarchy()
        }

        val duration = System.currentTimeMillis() - startTime
        Analytics.trackEvent(PrintHierarchyFinishedEvent(
            platform = platform,
            success = true,
            durationMs = duration
        ))
        Analytics.flush()
    }
}
