/*
 *
 *  Copyright (c) 2022 mobile.dev inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *
 */

package maestro.cli.command

import kotlinx.coroutines.runBlocking
import maestro.cli.App
import maestro.cli.DisableAnsiMixin
import maestro.cli.ShowHelpMixin
import maestro.cli.session.MaestroSessionManager
import maestro.cli.util.studioDownloadUrlForCurrentOs
import maestro.cli.view.red
import maestro.device.Platform
import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Model
import picocli.CommandLine.Option
import picocli.CommandLine.Spec

@Command(
    name = "query",
    description = [
        "Find elements in the view hierarchy of the connected device"
    ],
    hidden = true
)
class QueryCommand : Runnable {

    @CommandLine.Mixin
    var disableANSIMixin: DisableAnsiMixin? = null

    @CommandLine.Mixin
    var showHelpMixin: ShowHelpMixin? = null

    @CommandLine.ParentCommand
    private val parent: App? = null

    @Option(names = ["text"])
    private var text: String? = null

    @Option(names = ["id"])
    private var id: String? = null

    @Spec
    lateinit var commandSpec: Model.CommandSpec

    @Option(
        names = ["--apple-team-id"],
        description = ["The Team ID is a unique 10-character string generated by Apple that is assigned to your team's apple account."],
        hidden = true
    )
    private var appleTeamId: String? = null

    override fun run() {
        if (text == null && id == null) {
            throw CommandLine.ParameterException(
                commandSpec.commandLine(),
                "Must specify at least one search criteria"
            )
        }

        // W4: `query` matched against the legacy view hierarchy. Its device read now routes to the
        // device-core seam via `driver.hierarchy()`, a roadmap verb that throws NotImplemented until
        // device-core ships a hierarchy dump — the intended coverage signal. The host-side element
        // matching/output is gone with the legacy `Filters` path.
        MaestroSessionManager.newDeviceCoreSession(
            host = parent?.host,
            port = parent?.port,
            driverHostPort = parent?.driverHostPort,
            deviceId = parent?.deviceId,
            platform = parent?.platform?.let { Platform.fromString(it) },
        ) { driver, _, _ ->
            runBlocking { driver.hierarchy() }
        }
        System.err.println("This command is deprecated. Download the Maestro Studio desktop app instead: ${studioDownloadUrlForCurrentOs()}".red())
    }

}
