name: Publish Release

on:
  push:
    tags:
      - 'v*'

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'mobile-dev-inc/conductor'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - uses: gradle/gradle-build-action@v2

      - name: Retrieve version
        run: |
          echo "VERSION_NAME=$(cat gradle.properties | grep -w "VERSION_NAME" | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Upload Conductor client release
        run: ./gradlew clean :conductor-client:publish --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Upload Conductor ios release
        run: ./gradlew clean :conductor-ios:publish --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Upload Conductor orchestra release
        run: ./gradlew clean :conductor-orchestra:publish --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Upload Conductor Orchestra Models release
        run: ./gradlew clean :conductor-orchestra-models:publish --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Upload Conductor Proto release
        run: ./gradlew clean :conductor-proto:publish --no-daemon --no-parallel
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}