name: Publish Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'mobile-dev-inc/conductor'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/gradle-build-action@v2

      - name: Retrieve version
        run: |
          echo "VERSION_NAME=$(cat gradle.properties | grep -w "VERSION_NAME" | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Upload Conductor client release
        run: cd conductor-client && ../gradlew publish --no-daemon --no-parallel && ../gradlew closeAndReleaseRepository && cd ..
        if: endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Upload Conductor ios release
        run: cd conductor-ios && ../gradlew publish --no-daemon --no-parallel && ../gradlew closeAndReleaseRepository && cd ..
        if: endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Upload Conductor orchestra release
        run: cd conductor-orchestra && ../gradlew publish --no-daemon --no-parallel && ../gradlew closeAndReleaseRepository && cd ..
        if: endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Upload Conductor Orchestra Models release
        run: cd conductor-orchestra-models && ../gradlew publish --no-daemon --no-parallel && ../gradlew closeAndReleaseRepository && cd ..
        if: endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Upload Conductor Proto release
        run: cd conductor-proto && ../gradlew publish --no-daemon --no-parallel && ../gradlew closeAndReleaseRepository && cd ..
        if: endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}