name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'mobile-dev-inc/maestro'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test
        run: ./gradlew test


  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
