name: Warn Build XCTest runner

on:
  pull_request:
    paths:
      - 'maestro-ios-xctest-runner/**'

jobs:
  warn:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: "Make sure to run ./maestro-ios-xctest-runner/build-maestro-ios-runner.sh with every swift change"
